spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_db
    username: fintrack
    password: fintrack
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8082
